### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(UntitledProject)
add_subdirectory(UntitledProjectContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    UntitledProjectplugin
    UntitledProjectContentplugin)