spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  # Use "create" for fresh DB (removes data), or "none" for manual schema
spring.jpa.show-sql=true  # To log SQL queries (optional)
